global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'movieseat-frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['frontend:3000', 'app:3000']

  - job_name: 'movieseat-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8085']
